---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: regulated
  url: https://github.com/mspnp/aks-secure-baseline
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 2m
  path: "./k8s-resources/flux-system/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
