apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: falco
resources:
- namespace.yaml
- limit-range.yaml
- resource-quota.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- serviceaccount.yaml
- configmap.yaml
- daemonset.yaml
- deployment.yaml
images:
- name: falcosecurity/event-generator
  newName: REPLACE_ME_WITH_YOUR_ACRNAME.azurecr.io/falcosecurity/event-generator
  newTag: 0.6.0
- name: MYACR.azurecr.io/falcosecurity/falco
  newName: REPLACE_ME_WITH_YOUR_ACRNAME.azurecr.io/falcosecurity/falco