apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: falco
resources:
- namespace.yaml
- limit-range.yaml
- resource-quota.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- serviceaccount.yaml
- configmap.yaml
- daemonset.yaml
- deployment.yaml