  
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    requests.storage: "0"
    limits.cpu: "2"
    limits.memory: 2Gi
    count/persistentvolumeclaims: "0"
    count/services.loadbalancers: "0"
    count/deployments.apps: "10"
    count/services: "10"
    count/pods: "10"