  
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
spec:
  hard:
    requests.cpu: "300"
    requests.memory: 30Gi
    requests.storage: "0"
    limits.cpu: "300"
    limits.memory: 300Gi
    count/persistentvolumeclaims: "0"
    count/services.loadbalancers: "0"
    count/deployments.apps: "100"
    count/services: "100"
    count/pods: "100"